# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pw',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/pw',
                'lib_path': 'pw'},
  'syms': { 'pw.core': { 'pw.core.BrowserCleanupError': ('core.html#browsercleanuperror', 'pw/core.py'),
                         'pw.core.BrowserResources': ('core.html#browserresources', 'pw/core.py'),
                         'pw.core.PageCreationError': ('core.html#pagecreationerror', 'pw/core.py'),
                         'pw.core._frames_ready': ('core.html#_frames_ready', 'pw/core.py'),
                         'pw.core._page_ready': ('core.html#_page_ready', 'pw/core.py'),
                         'pw.core.find_ele': ('core.html#find_ele', 'pw/core.py'),
                         'pw.core.retry_async': ('core.html#retry_async', 'pw/core.py'),
                         'pw.core.setup_browser': ('core.html#setup_browser', 'pw/core.py'),
                         'pw.core.wait_page': ('core.html#wait_page', 'pw/core.py')}}}
